apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: obs-syscd-live
  namespace: external-dns
spec:
  endpoints:
    - dnsName: obs.syscd.live
      recordTTL: 1
      recordType: CNAME
      targets:
        - 248f4b51-d33d-4896-89c1-acb748c54330.cfargotunnel.com
