apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret-2
  namespace: obs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-secret-2
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: cloudflare-tunnel-secret-2
