{
 "title": "Kubernetes Pod Dashboard",
 "description": "Dashboard for kubernetes pod",
 "tags": [
  "syscd",
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-kube_pod_start_time{namespace=\"$namespace\", pod=\"$pod\", app=\"\"}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\", pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[$duration])))"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[$duration])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Memory(%)"
    }
   ]
  },
  {
   "title": "Resource Request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Resource Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory (Swap/Hits Limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{namespace=\"$namespace\", pod=\"$pod\"}[$duration])) by (pod)",
     "legendFormat": "Hits limits"
    }
   ]
  },
  {
   "title": "Out of Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(round(increase(container_oom_events_total{namespace=\"$namespace\", pod=\"$pod\"}[$duration])))",
     "legendFormat": "OOM"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$duration]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$duration]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Number of Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\"})",
     "legendFormat": "Thread"
    }
   ]
  }
 ]
}