{{- if .Values.podMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app: atenet-router
  name: atenet-router-envoy
  namespace: ate-system
spec:
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: admin
  selector:
    matchLabels:
      app: atenet-router

{{- end }}
