apiVersion: v1
kind: ServiceAccount
metadata:
  name: ate-api-server
  namespace: ate-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    apps: ate-client
  name: ate-client
  namespace: ate-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    apps: ate-controller
  name: ate-controller
  namespace: ate-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atelet
  namespace: ate-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: atenet-router
  name: atenet-router
  namespace: ate-system
