{{- if .Values.features.defaultLimitRange }}
{{- range .Values.limitRanges.namespaces }}
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resources
  namespace: {{ . }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml $.Values.limitRanges.default | nindent 8 }}
      defaultRequest:
        {{- toYaml $.Values.limitRanges.defaultRequest | nindent 8 }}
---
{{- end }}
{{- end }}
