apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mecak8s.fullname" . }}
  labels: {{- include "mecak8s.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mecak8s.fullname" . }}-lease-holder
  labels: {{- include "mecak8s.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mecak8s.fullname" . }}-lease-holder
  labels: {{- include "mecak8s.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mecak8s.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mecak8s.fullname" . }}-lease-holder
