{{- $pc := .Values.providerConfig.name }}
{{- $dp := .Values.deletionPolicy }}
{{- range .Values.serviceAccountKeys }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: {{ .name }}
spec:
  deletionPolicy: {{ .deletionPolicy | default $dp }}
  providerConfigRef:
    name: {{ $pc }}
  {{- with .writeConnectionSecretToRef }}
  writeConnectionSecretToRef:
    namespace: {{ .namespace }}
    name: {{ .name }}
  {{- end }}
  forProvider:
    serviceAccountIdRef:
      name: {{ .serviceAccountRef }}
    keyAlgorithm: {{ .keyAlgorithm | default "KEY_ALG_RSA_2048" }}
    {{- with .includeSecureJsonData }}
    includeSecureJsonData: {{ . }}
    {{- end }}
{{- end }}
