{
 "title": "My - WatchTower",
 "description": "An overview of things that can go wrong.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Over 80% of Limits",
   "type": "timeseries",
   "description": "Namespace/pod/container using more than 80% of CPU limits.\n\nNo data is good.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total\n{container!=\"\"}[5m])) / sum by (namespace,pod,container)\n(kube_pod_container_resource_limits{resource=\"cpu\"})) > 0.8",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}}"
    }
   ]
  },
  {
   "title": "Containers Memory Usage Over 80% of Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (namespace,pod,container)(container_memory_working_set_bytes{container!=\"\"}) / sum by (namespace,pod,container)(kube_pod_container_resource_limits{container!=\"\", resource=\"memory\"})) > 0.8",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Containers WITHOUT CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace,container)(count by (namespace,pod,container)(kube_pod_container_info{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Containers WITHOUT Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace,container)(count by (namespace,pod,container)(kube_pod_container_info{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"}))",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Container WITHOUT CPU Limits Using More CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers WITHOUT Memory Limits Using More Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(container_memory_usage_bytes{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"}))",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Alerts Overview", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } }
 ]
}