{
 "title": "Kubernetes / Autoscaling / Vertical Pod Autoscaler",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for vertical pod autoscalers. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "syscd",
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "kubernetes-core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{job=~\"$job\"}, namespace)"
   },
   {
    "name": "vpa",
    "label": "VPA Pod Autoscaler",
    "query": "label_values(kube_customresource_verticalpodautoscaler_labels{job=~\"$job\", namespace=~\"$namespace\"}, verticalpodautoscaler)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{job=~\"$job\", namespace=~\"$namespace\", verticalpodautoscaler=~\"$vpa\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "$namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Resource Recommendations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Lower Bound"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Target"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Upper Bound"
    }
   ]
  },
  {
   "title": "Memory Resource Recommendations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Lower Bound"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Target"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Upper Bound"
    }
   ]
  },
  { "title": "$vpa / $container Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "container" },
  {
   "title": "CPU Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Memory Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Memory Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Lower Bound"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Target"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"cpu\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Upper Bound"
    },
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa-(.+)\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Usage"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa-(.+)\",\n    resource=\"cpu\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa-(.+)\",\n    resource=\"cpu\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Limits"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Lower Bound"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Target"
    },
    {
     "expr": "sum(\n  kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{\n    job=~\"$job\",\n    namespace=~\"$namespace\",\n    resource=\"memory\",\n    verticalpodautoscaler=\"$vpa\",\n    container=\"$container\"\n  }\n) by (job, namespace, verticalpodautoscaler, container, resource)\n",
     "legendFormat": "{{ container }} - Upper Bound"
    },
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa(.+)\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Usage"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa-(.+)\",\n    resource=\"memory\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Requests"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{\n    job=~\"$job\",\n    namespace=\"$namespace\",\n    pod=~\"$vpa-(.+)\",\n    resource=\"memory\",\n    container=\"$container\"\n  }\n) by (container)\n",
     "legendFormat": "{{ container }} - Limits"
    }
   ]
  }
 ]
}