{
 "title": "My - Kubernetes / Capacity Planning / Limits",
 "description": "Provides information relevant to fine-tuning container resource limits in Kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container!='POD', node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container!='POD', node=~\"$node\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container!='POD', node=~\"$node\", namespace=~\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Available CPU",
   "type": "graph",
   "description": "Shows CPU used vs. allocatable CPU",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{instance=~\"$node\", mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "Available cores ({{ instance }})"
    }
   ]
  },
  {
   "title": "CPU limits used",
   "type": "graph",
   "description": "CPU usage relative to the CPU limits",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "% of limits" }
   ],
   "targets": [
    {
     "expr": "sum (\n  irate (\n    container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[2m]\n  )\n) by (namespace,pod,container)\n/\nsum (\n  container_spec_cpu_quota{image!=\"\",container!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n) by (namespace,pod,container)\n*\n10000000",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "description": "Shows memory used vs. allocatable memory",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$node\"}) by (instance)/1024^3",
     "legendFormat": "Available memory ({{ instance }})"
    }
   ]
  },
  {
   "title": "Memory limits used",
   "type": "graph",
   "description": "Memory usage relative to the memory limits",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "% of limits used" }
   ],
   "targets": [
    {
     "expr": "(\n  sum (\n    container_memory_working_set_bytes{container!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n  ) by (namespace,pod,container)\n  /\n  sum (\n    container_spec_memory_limit_bytes{container!=\"POD\",node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n  ) by (namespace,pod,container)\n) * 100",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  }
 ]
}