{
 "title": "My - Workload Resource Recommendations Based on Usage",
 "description": "Recommended Requests & Limits for Kubernetes Workloads based on historical usage",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=\"$namespace\"},owner_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\",pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=\"$namespace\",owner_name=\"$controller\"},pod)"
    }
   },
   { "name": "memory_overhead_percent", "query": "50,0,10,25,100" },
   { "name": "cpu_percentile", "query": "0.95,0.5,0.75,0.9,0.99,0.999" },
   { "name": "memory_percentile", "query": "0.99,0.5,0.75,0.9,0.95,0.999" },
   { "name": "cpu_overhead_percent", "query": "10,0,5,25,50,100" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$pod\", cluster=\"$cluster\", container=~\"$container\"}) by (pod)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", container=~\"$container\"}) by (container))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", container=~\"$container\"}) by (container))\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Suggested CPU Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 + ($cpu_overhead_percent/100) ) * max(quantile_over_time($cpu_percentile,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$pod\", cluster=\"$cluster\", container=~\"$container\"}) by (pod,namespace,container)[$__range:15m]) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Suggested CPU Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "2 * ( 1 + ($cpu_overhead_percent/100) ) * max(quantile_over_time($cpu_percentile,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$pod\", cluster=\"$cluster\", container=~\"$container\"}) by (pod,namespace,container)[$__range:15m]) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"})"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(\n    avg(\n      kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", container=~\"$container\"}\n    ) by (container)\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    avg(\n      kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", container=~\"$container\"}\n    ) by (container)\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Suggested Memory Request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 + ($memory_overhead_percent/100) ) * max(avg(quantile_over_time($memory_percentile,container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\", container=~\"$container\"}[$__range])) by (pod,namespace,container) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Suggested Memory Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 + ($memory_overhead_percent/100) ) * max(avg(quantile_over_time($memory_percentile,container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\", container=~\"$container\"}[$__range])) by (pod,namespace,container) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"}) "
    }
   ]
  }
 ]
}