{{- if .Values.longhornBackupTarget.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.longhornBackupTarget.secretName | default "longhorn-backup-target" }}
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.longhornBackupTarget.secretName | default "longhorn-backup-target" }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        # Format: s3://bucket-name@region/
        backupTarget: "{{`{{ .backupTarget }}`}}"
  dataFrom:
    - extract:
        key: {{ .Values.longhornBackupTarget.onePasswordItem | quote }}
{{- end }}
