{{- range .Values.secrets | default (list) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
type: {{ default "Opaque" .type }}
{{- if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}
