apiVersion: apps/v1
kind: Deployment
metadata:
  name: ax-redis
  namespace: ax-system
  labels:
    app.kubernetes.io/name: ax-redis
    app.kubernetes.io/part-of: {{ include "ax.partOf" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ax-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ax-redis
        app.kubernetes.io/part-of: {{ include "ax.partOf" . }}
    spec:
      nodeSelector:
        {{- include "ax.nodeSelector" . | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ax-redis
  namespace: ax-system
  labels:
    app.kubernetes.io/name: ax-redis
    app.kubernetes.io/part-of: {{ include "ax.partOf" . }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app.kubernetes.io/name: ax-redis
