apiVersion: v1
kind: ServiceAccount
metadata:
  name: ax-controller
  namespace: ax-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ax-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ax-controller
subjects:
  - kind: ServiceAccount
    name: ax-controller
    namespace: ax-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ax-controller
