{{- if eq .Values.monitoringProvider "victoriametrics" }}
# VMServiceScrape for cert-manager
# Replaces Prometheus Operator ServiceMonitor
# https://cert-manager.io/docs/devops-tips/prometheus-metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  endpoints:
  - port: tcp-prometheus-servicemonitor
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
  namespaceSelector:
    matchNames:
    - cert-manager
{{- end }}
