# test: https://blackbox-exporter.syscd.live/probe?module=http_2xx&target=http://zigbee2mqtt.zigbee2mqtt.svc.cluster.local:8080/health&debug=true
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: zigbee2mqtt
  namespace: monitoring
spec:
  jobName: "probe/monitoring/zigbee2mqtt"
  interval: 30s
  module: http_2xx
  vmProberSpec:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      targets:
        - http://zigbee2mqtt.zigbee2mqtt.svc.cluster.local:8080
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: zigbee2mqtt-rules
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: zigbee2mqtt.rules
      rules:
        - alert: Zigbee2MQTTDown
          expr: probe_success{job="probe/monitoring/zigbee2mqtt"} == 0
          for: 5m
          labels:
            severity: critical
            service: zigbee2mqtt
          annotations:
            summary: "Zigbee2MQTT is down"
            description: "Zigbee2MQTT has been unreachable for more than 5 minutes." 