{{- if not .Values.operator.enabled }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (include "hermes-agent.fullname" .) .Values.externalSecret.name }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
    {{- with .Values.externalSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "hermes-agent.secretName" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | quote }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy | quote }}
    template:
      type: {{ .Values.externalSecret.target.template.type | quote }}
      metadata:
        annotations: {{ toYaml (default dict .Values.externalSecret.target.template.metadata.annotations) | nindent 10 }}
        labels: {{ toYaml (default dict .Values.externalSecret.target.template.metadata.labels) | nindent 10 }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
