{{- if not .Values.operator.enabled }}
{{- if and (not .Values.externalSecret.enabled) (not .Values.secrets.existingSecret) }}
{{- $keys := keys .Values.secrets | sortAlpha -}}
{{- $hasValues := false -}}
{{- range $keys }}
  {{- $value := index $.Values.secrets . -}}
  {{- if and (ne . "existingSecret") (ne . "annotations") (ne (printf "%v" $value) "") -}}
    {{- $hasValues = true -}}
  {{- end -}}
{{- end }}
{{- if $hasValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-agent.secretName" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $keys }}
  {{- $value := index $.Values.secrets . -}}
  {{- if and (ne . "existingSecret") (ne . "annotations") (ne (printf "%v" $value) "") }}
  {{ . }}: {{ tpl (printf "%v" $value) $ | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
