{
 "title": "Cloudders",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Status codes chart",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(healthcheck_response_codes{name=\"bing\"}[1m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "healthcheck_response_time{name=\"bing\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Health Check status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck_status{name=\"bing\"}"
    }
   ]
  },
  {
   "title": "Response time state",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "healthcheck_response_time{name=\"bing\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime timeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "healthcheck_status{name=\"bing\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}